table Dim_Vendor
	lineageTag: 63dab294-269a-42bf-b926-9f453d152cdc

	column No
		dataType: string
		isKey
		lineageTag: 1402b169-8720-4e4e-bfdf-75ac296b0e86
		summarizeBy: none
		sourceColumn: No.

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 20f7f662-9185-43ad-afb5-ed34cb0a6a62
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Currency_Code
		dataType: string
		lineageTag: 39890fc2-d4da-4755-938f-0ef63ae2a169
		summarizeBy: none
		sourceColumn: Currency Code

		annotation SummarizationSetBy = Automatic

	partition Dim_Vendor = m
		mode: import
		source =
				let
					Source = Dynamics365BusinessCentral.ApiContentsWithOptions(null, null, null, null),
					Environment = Source{[Name = BCEnvironment]}[Data],
					Company = Environment{[Name = BCCompanyName]}[Data],
					StandardV2 = Company{[Name = "v2.0"]}[Data],
					Vendor = StandardV2{[Name = "vendors"]}[Data],
					#"Selected Columns" = Table.SelectColumns(
						Vendor,
						{"number", "displayName", "currencyCode"},
						MissingField.UseNull
					),
					#"Renamed Columns" = Table.RenameColumns(
						#"Selected Columns",
						{{"number", "No."}, {"displayName", "Name"}, {"currencyCode", "Currency Code"}}
					),
					#"Changed Type" = Table.TransformColumnTypes(
						#"Renamed Columns",
						{{"No.", type text}, {"Name", type text}, {"Currency Code", type text}}
					)
				in
					#"Changed Type"

