table Dim_BusinessDimension1
	lineageTag: a1472056-63fc-4062-baaf-6022b2e86433

	column Code
		dataType: string
		isKey
		lineageTag: 813b1f34-40a0-4b3b-b1c6-53265362dc94
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 137dd647-53f7-4791-8b54-e05669bd2af6
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Dimension_Code
		dataType: string
		isHidden
		lineageTag: 33061ad8-349d-4f2e-b4c3-979346c665f8
		summarizeBy: none
		sourceColumn: Dimension Code

		annotation SummarizationSetBy = Automatic

	partition Dim_BusinessDimension1 = m
		mode: import
		source =
				let
					Source = Dynamics365BusinessCentral.ApiContentsWithOptions(null, null, null, null),
					Environment = Source{[Name = BCEnvironment]}[Data],
					Company = Environment{[Name = BCCompanyName]}[Data],
					StandardV2 = Company{[Name = "v2.0"]}[Data],
					Dimensions = StandardV2{[Name = "dimensions"]}[Data],
					DimensionValues = StandardV2{[Name = "dimensionValues"]}[Data],
					#"Filtered Dimension" = Table.SelectRows(Dimensions, each [code] = GlobalDimension1Code),
					TargetDimensionId = #"Filtered Dimension"{0}[id],
					#"Filtered Values" = Table.SelectRows(DimensionValues, each [dimensionId] = TargetDimensionId),
					#"Selected Columns" = Table.SelectColumns(#"Filtered Values", {"code", "displayName"}),
					#"Renamed Columns" = Table.RenameColumns(#"Selected Columns", {{"code", "Code"}, {"displayName", "Name"}}),
					#"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Code", type text}, {"Name", type text}}),
					#"Added Dimension Code" = Table.AddColumn(#"Changed Type", "Dimension Code", each GlobalDimension1Code, type text),
					#"Added Blank Row" = Table.Combine({#"Added Dimension Code", #table(type table [Code = text, Name = text, #"Dimension Code" = text], {{"", "(No Department)", GlobalDimension1Code}})})
				in
					#"Added Blank Row"

