table Dim_BusinessDimension2
	lineageTag: b3b849f2-e60b-4388-89fc-c834803434c9

	column Code
		dataType: string
		isKey
		lineageTag: c0ceb0f3-fdf8-45e0-b2aa-9ffcaa641160
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 65729aeb-8386-4cec-8f80-7d87f4d02f88
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Dimension_Code
		dataType: string
		isHidden
		lineageTag: 69d25a9a-2262-40e8-8d06-9007eb9618b5
		summarizeBy: none
		sourceColumn: Dimension Code

		annotation SummarizationSetBy = Automatic

	partition Dim_BusinessDimension2 = m
		mode: import
		source =
				let
					Source = Dynamics365BusinessCentral.ApiContentsWithOptions(null, null, null, null),
					Environment = Source{[Name = BCEnvironment]}[Data],
					Company = Environment{[Name = BCCompanyName]}[Data],
					StandardV2 = Company{[Name = "v2.0"]}[Data],
					Dimensions = StandardV2{[Name = "dimensions"]}[Data],
					DimensionValues = StandardV2{[Name = "dimensionValues"]}[Data],
					#"Filtered Dimension" = Table.SelectRows(Dimensions, each [code] = GlobalDimension2Code),
					TargetDimensionId = #"Filtered Dimension"{0}[id],
					#"Filtered Values" = Table.SelectRows(DimensionValues, each [dimensionId] = TargetDimensionId),
					#"Selected Columns" = Table.SelectColumns(#"Filtered Values", {"code", "displayName"}),
					#"Renamed Columns" = Table.RenameColumns(#"Selected Columns", {{"code", "Code"}, {"displayName", "Name"}}),
					#"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Code", type text}, {"Name", type text}}),
					#"Added Dimension Code" = Table.AddColumn(#"Changed Type", "Dimension Code", each GlobalDimension2Code, type text),
					#"Added Blank Row" = Table.Combine({#"Added Dimension Code", #table(type table [Code = text, Name = text, #"Dimension Code" = text], {{"", "(No Customer Group)", GlobalDimension2Code}})})
				in
					#"Added Blank Row"

