table Dim_ChartOfAccounts
	lineageTag: e371108a-7aa1-4d20-b307-6ee29ec2966a

	column Name
		dataType: string
		lineageTag: 9cbc5cb7-1577-4276-938c-37cfa8ade464
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Totaling
		dataType: string
		lineageTag: f84efea0-552a-4c34-83da-45ea0eeb7fa7
		summarizeBy: none
		sourceColumn: Totaling

		annotation SummarizationSetBy = Automatic

	column Indentation
		dataType: int64
		formatString: 0
		lineageTag: 3045e6f6-93b1-4960-bc69-3ca2a5170064
		summarizeBy: sum
		sourceColumn: Indentation

		annotation SummarizationSetBy = Automatic

	column Debit_Credit
		dataType: string
		lineageTag: 42c3d997-5bf5-4ceb-a31a-5c9acda5d5c2
		summarizeBy: none
		sourceColumn: Debit/Credit

		annotation SummarizationSetBy = Automatic

	column No
		dataType: string
		lineageTag: 77b1b659-cd12-4b63-92b8-949ae7212f08
		summarizeBy: none
		sourceColumn: No

		annotation SummarizationSetBy = Automatic

	column Account_Type
		dataType: string
		lineageTag: 362b5863-4d03-4ae5-a55b-ab0b95b692a3
		summarizeBy: none
		sourceColumn: Account_Type

		annotation SummarizationSetBy = Automatic

	column Income_Balance
		dataType: string
		lineageTag: d118c951-1eb2-4ea1-b8ed-520b679c75e5
		summarizeBy: none
		sourceColumn: Income_Balance

		annotation SummarizationSetBy = Automatic

	column Debit_Amount
		dataType: double
		lineageTag: f144b2ab-712d-45f0-889e-376c1937518a
		summarizeBy: sum
		sourceColumn: Debit_Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Credit_Amount
		dataType: double
		lineageTag: 39275281-75e4-4e84-b5c8-859f8dcde335
		summarizeBy: sum
		sourceColumn: Credit_Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Account_Category
		dataType: string
		lineageTag: d75c2afe-9d18-402a-831c-518c7ea5f316
		summarizeBy: none
		sourceColumn: Account_Category

		annotation SummarizationSetBy = Automatic

	column Account_Subcategory_Descript
		dataType: string
		lineageTag: f4a841ce-798d-4567-b2fd-43d28f0696f9
		summarizeBy: none
		sourceColumn: Account_Subcategory_Descript

		annotation SummarizationSetBy = Automatic

	partition Dim_ChartOfAccounts = m
		mode: import
		source =
				let
					Source = Dynamics365BusinessCentral.ApiContentsWithOptions(null, null, null, null),
					Environment = Source{[Name = BCEnvironment]}[Data],
					Company = Environment{[Name = BCCompanyName]}[Data],
					WebServices = Company{[Name = "WebServices"]}[Data],
					#"Chart of Accounts" = WebServices{[Name = "Chart_of_Accounts"]}[Data],
					#"Selected Columns" = Table.SelectColumns(
						#"Chart of Accounts",
						{
							"No", "Name", "Account_Type", "Income_Balance", "Debit_Amount","Credit_Amount",
							"Account_Category", "Account_Subcategory_Descript", "Totaling",
							"Indentation", "Blocked"
						},
						MissingField.UseNull
					),
					#"Filtered Rows" = Table.SelectRows(#"Selected Columns", each [Blocked] <> true),
					#"Removed Columns" = Table.RemoveColumns(#"Filtered Rows", {"Blocked"}),
					#"Changed Type" = Table.TransformColumnTypes(
						#"Removed Columns",
						{
							{"No", type text}, {"Name", type text}, {"Account_Type", type text},
							{"Income_Balance", type text}, {"Debit_Amount", type number},{"Credit_Amount", type number},
							{"Account_Category", type text}, {"Account_Subcategory_Descript", type text},
							{"Totaling", type text}, {"Indentation", Int64.Type}
						}
					),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Debit/Credit", each [Debit_Amount]-[Credit_Amount])
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

