table Dim_Customer
	lineageTag: 73845ae6-a53f-450f-b432-91800b3c0ad5

	column No
		dataType: string
		isKey
		lineageTag: 2b23123c-4c3c-4b09-aa01-189ab122657e
		summarizeBy: none
		sourceColumn: No.

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: b713cac2-2553-447b-969a-af4e3f54a22b
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Currency_Code
		dataType: string
		lineageTag: a1236e58-3482-4f56-8bd1-7d22fe73b9e2
		summarizeBy: none
		sourceColumn: Currency Code

		annotation SummarizationSetBy = Automatic

	partition Dim_Customer = m
		mode: import
		source =
				let
					Source = Dynamics365BusinessCentral.ApiContentsWithOptions(null, null, null, null),
					Environment = Source{[Name = BCEnvironment]}[Data],
					Company = Environment{[Name = BCCompanyName]}[Data],
					StandardV2 = Company{[Name = "v2.0"]}[Data],
					Customer = StandardV2{[Name = "customers"]}[Data],
					#"Selected Columns" = Table.SelectColumns(
						Customer,
						{"number", "displayName", "currencyCode"},
						MissingField.UseNull
					),
					#"Renamed Columns" = Table.RenameColumns(
						#"Selected Columns",
						{{"number", "No."}, {"displayName", "Name"}, {"currencyCode", "Currency Code"}}
					),
					#"Changed Type" = Table.TransformColumnTypes(
						#"Renamed Columns",
						{{"No.", type text}, {"Name", type text}, {"Currency Code", type text}}
					)
				in
					#"Changed Type"

