table Fact_GLTransactions
	lineageTag: 88df298c-abfb-40d6-bbac-9091461943ce

	column Description
		dataType: string
		lineageTag: a12a344d-6d52-4c95-a39a-57d3f2751105
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: double
		formatString: \$#,0.00;(\$#,0.00)
		lineageTag: f1c9073c-ca8e-43e3-a96d-36effd2a64d1
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Entry_No
		dataType: int64
		formatString: 0
		lineageTag: 0efb95a3-3bc0-470f-92d1-5530ede35759
		summarizeBy: none
		sourceColumn: Entry_No

		annotation SummarizationSetBy = Automatic

	column G_L_Account_No
		dataType: string
		lineageTag: 210fe32e-33f8-4b9e-9e9b-395d5c97c7f3
		summarizeBy: none
		sourceColumn: G_L_Account_No

		annotation SummarizationSetBy = Automatic

	column Posting_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 25f8b61a-56db-41aa-8a1e-1ea6b10feae7
		summarizeBy: none
		sourceColumn: Posting_Date

		variation Variation
			isDefault
			relationship: a1fd6b37-30f3-47ce-810c-aa9ebbb8be43
			defaultHierarchy: LocalDateTable_b8049046-1f7e-44a9-a7cd-77e123fb44e8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Document_No
		dataType: string
		lineageTag: 8b34cccb-70f1-4590-93b9-d30c81501d21
		summarizeBy: none
		sourceColumn: Document_No

		annotation SummarizationSetBy = Automatic

	column Document_Type
		dataType: string
		lineageTag: 8d5f81ce-b497-414b-87f2-7a194a455672
		summarizeBy: none
		sourceColumn: Document_Type

		annotation SummarizationSetBy = Automatic

	column Source_Code
		dataType: string
		lineageTag: 62b872ed-6b98-4feb-97b2-afe2ee2ca636
		summarizeBy: none
		sourceColumn: Source_Code

		annotation SummarizationSetBy = Automatic

	column Global_Dimension_1_Code
		dataType: string
		lineageTag: 69063df1-f6dc-4ca5-8c2f-34af0526174a
		summarizeBy: none
		sourceColumn: Global_Dimension_1_Code

		annotation SummarizationSetBy = Automatic

	column Global_Dimension_2_Code
		dataType: string
		lineageTag: 9e08cc0c-384b-49bf-81ab-77553aac5cb9
		summarizeBy: none
		sourceColumn: Global_Dimension_2_Code

		annotation SummarizationSetBy = Automatic

	column Debit_Amount
		dataType: double
		lineageTag: fabc6aea-d6e4-4a02-9b80-ee80cf198636
		summarizeBy: sum
		sourceColumn: Debit_Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Credit_Amount
		dataType: double
		lineageTag: eed16e93-db5f-4405-81bb-2aafec5f584d
		summarizeBy: sum
		sourceColumn: Credit_Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column User_ID
		dataType: string
		lineageTag: acd6a14c-c964-4cbb-ae6e-b75d2d5a7f03
		summarizeBy: none
		sourceColumn: User_ID

		annotation SummarizationSetBy = Automatic

	partition Fact_GLTransactions = m
		mode: import
		source =
				let
					Source = Dynamics365BusinessCentral.ApiContentsWithOptions(null, null, null, null),
					Environment = Source{[Name = BCEnvironment]}[Data],
					Company = Environment{[Name = BCCompanyName]}[Data],
					WebServices = Company{[Name = "WebServices"]}[Data],
					#"G/L Entries" = WebServices{[Name = "G_LEntries"]}[Data],
					#"Selected Columns" = Table.SelectColumns(
						#"G/L Entries",
						{
							"Entry_No", "G_L_Account_No", "Posting_Date", "Document_No", "Document_Type",
							"Description", "Source_Code", "Global_Dimension_1_Code", "Global_Dimension_2_Code",
							"Debit_Amount", "Credit_Amount", "Amount", "User_ID"
						},
						MissingField.UseNull
					),
					#"Changed Type" = Table.TransformColumnTypes(
						#"Selected Columns",
						{
							{"Entry_No", Int64.Type}, {"G_L_Account_No", type text}, {"Posting_Date", type datetime},
							{"Document_No", type text}, {"Document_Type", type text}, {"Description", type text},
							{"Source_Code", type text}, {"Global_Dimension_1_Code", type text},
							{"Global_Dimension_2_Code", type text}, {"Debit_Amount", type number},
							{"Credit_Amount", type number}, {"Amount", type number}, {"User_ID", type text}
						}
					),
					#"Filtered Rows" = Table.SelectRows(
						#"Changed Type",
						each [Posting_Date] >= RangeStart and [Posting_Date] < RangeEnd
					)
				in
					#"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

