table Fact_CustLedgerEntries
	lineageTag: 2990c109-7994-4903-886f-d855ff610158

	column Description
		dataType: string
		lineageTag: 4e7b2b25-aee5-4c1d-a667-f8093c69d2d1
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Open
		dataType: boolean
		lineageTag: 9adea10e-1972-49f2-9815-e93cafbe6c32
		summarizeBy: none
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: double
		formatString: \$#,0.00;(\$#,0.00)
		lineageTag: 0a84bcc8-3ec1-41c5-a20d-84b1b191a836
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Entry_No
		dataType: int64
		formatString: 0
		lineageTag: 81c4955a-7e47-441d-a883-60992a67732f
		summarizeBy: sum
		sourceColumn: Entry_No

		annotation SummarizationSetBy = Automatic

	column Customer_No
		dataType: string
		lineageTag: df7b039d-835b-43be-bcf3-5f6f64da547c
		summarizeBy: none
		sourceColumn: Customer_No

		annotation SummarizationSetBy = Automatic

	column Posting_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: a6e05368-d3a3-4071-aa9b-9fe09a6c7de1
		summarizeBy: none
		sourceColumn: Posting_Date

		annotation SummarizationSetBy = Automatic

	column Due_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: a050c5ac-46b5-4fcb-a123-7e1ee85a1dec
		summarizeBy: none
		sourceColumn: Due_Date

		variation Variation
			isDefault
			relationship: b701e14e-cdf2-4146-94aa-d7e05d28f4bc
			defaultHierarchy: LocalDateTable_ffc56e92-d303-4c7d-af49-d61eab56d995.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Document_Type
		dataType: string
		lineageTag: d2ab9770-9110-480b-ad4c-89f3ead26622
		summarizeBy: none
		sourceColumn: Document_Type

		annotation SummarizationSetBy = Automatic

	column Document_No
		dataType: string
		lineageTag: 61ca516c-6c8e-4fb3-a2e2-74d75efa6e1f
		summarizeBy: none
		sourceColumn: Document_No

		annotation SummarizationSetBy = Automatic

	column Currency_Code
		dataType: string
		lineageTag: 807f8178-1b6d-418f-9482-8aa1a1f5b888
		summarizeBy: none
		sourceColumn: Currency_Code

		annotation SummarizationSetBy = Automatic

	column Remaining_Amount
		dataType: double
		lineageTag: fe66e56d-f86a-46e9-8795-cda024f6cb63
		summarizeBy: sum
		sourceColumn: Remaining_Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_CustLedgerEntries = m
		mode: import
		source =
				let
					Source = Dynamics365BusinessCentral.ApiContentsWithOptions(null, null, null, null),
					Environment = Source{[Name = BCEnvironment]}[Data],
					Company = Environment{[Name = BCCompanyName]}[Data],
					WebServices = Company{[Name = "WebServices"]}[Data],
					#"Cust. Ledger Entries" = WebServices{[Name = "Cust_LedgerEntries"]}[Data],
					#"Selected Columns" = Table.SelectColumns(
						#"Cust. Ledger Entries",
						{
							"Entry_No", "Customer_No", "Posting_Date", "Due_Date", "Document_Type",
							"Document_No", "Description", "Currency_Code", "Open", "Amount", "Remaining_Amount"
						},
						MissingField.UseNull
					),
					#"Changed Type" = Table.TransformColumnTypes(
						#"Selected Columns",
						{
							{"Entry_No", Int64.Type}, {"Customer_No", type text}, {"Posting_Date", type datetime},
							{"Due_Date", type datetime}, {"Document_Type", type text}, {"Document_No", type text},
							{"Description", type text}, {"Currency_Code", type text}, {"Open", type logical},
							{"Amount", type number}, {"Remaining_Amount", type number}
						}
					),
					#"Filtered Blank Keys" = Table.SelectRows(#"Changed Type", each Record.Field(_, "Entry_No") <> null)
				in
					#"Filtered Blank Keys"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

