table Fact_VendorLedgerEntries
	lineageTag: e418689f-36fe-4df8-a84e-b985cb894841

	column Description
		dataType: string
		lineageTag: a9683e63-b29d-41bc-802d-db1c7ff41fc7
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Open
		dataType: boolean
		lineageTag: c9973b6d-3a4e-4954-a444-ae2723986ad5
		summarizeBy: none
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: double
		formatString: \$#,0.00;(\$#,0.00)
		lineageTag: 25ddee51-42d9-4ed5-bab3-10383fcf8556
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Entry_No
		dataType: int64
		formatString: 0
		lineageTag: cebff395-5d81-46a6-b125-5b4dd4456809
		summarizeBy: none
		sourceColumn: Entry_No

		annotation SummarizationSetBy = Automatic

	column Vendor_No
		dataType: string
		lineageTag: 6f03401c-17ea-4e0a-bd87-f87e7d212908
		summarizeBy: none
		sourceColumn: Vendor_No

		annotation SummarizationSetBy = Automatic

	column Posting_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 430876d1-f594-4614-8595-633d6f81b6e9
		summarizeBy: none
		sourceColumn: Posting_Date

		variation Variation
			isDefault
			relationship: 5b1ec391-12d6-4d55-8000-e067d7541b3c
			defaultHierarchy: LocalDateTable_a6e27b79-64df-47ae-b2bb-e8ac93ead9b6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Due_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 791be172-7786-46dd-8276-ed9da0628c68
		summarizeBy: none
		sourceColumn: Due_Date

		variation Variation
			isDefault
			relationship: 4b52779f-a63e-460e-8efd-a06ee3683051
			defaultHierarchy: LocalDateTable_a0c7b532-ae1c-4844-90ba-e6c5dbec2a77.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Document_Type
		dataType: string
		lineageTag: 9d1d77e5-68cd-41f6-84dd-75dae717130f
		summarizeBy: none
		sourceColumn: Document_Type

		annotation SummarizationSetBy = Automatic

	column Document_No
		dataType: string
		lineageTag: 80876f26-8b52-4d40-a0bd-bccb0d3848e5
		summarizeBy: none
		sourceColumn: Document_No

		annotation SummarizationSetBy = Automatic

	column Currency_Code
		dataType: string
		lineageTag: c877f8d7-fb3b-46e4-bffb-0c41522dc380
		summarizeBy: none
		sourceColumn: Currency_Code

		annotation SummarizationSetBy = Automatic

	column Remaining_Amount
		dataType: double
		lineageTag: c0dd8fb2-115a-4939-aaf8-7cc33ea51c2f
		summarizeBy: sum
		sourceColumn: Remaining_Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_VendorLedgerEntries = m
		mode: import
		source =
				let
					Source = Dynamics365BusinessCentral.ApiContentsWithOptions(null, null, null, null),
					Environment = Source{[Name = BCEnvironment]}[Data],
					Company = Environment{[Name = BCCompanyName]}[Data],
					WebServices = Company{[Name = "WebServices"]}[Data],
					#"Vendor Ledger Entries" = WebServices{[Name = "VendorLedgerEntries"]}[Data],
					#"Selected Columns" = Table.SelectColumns(
						#"Vendor Ledger Entries",
						{
							"Entry_No", "Vendor_No", "Posting_Date", "Due_Date", "Document_Type",
							"Document_No", "Description", "Currency_Code", "Open", "Amount", "Remaining_Amount"
						},
						MissingField.UseNull
					),
					#"Changed Type" = Table.TransformColumnTypes(
						#"Selected Columns",
						{
							{"Entry_No", Int64.Type}, {"Vendor_No", type text}, {"Posting_Date", type datetime},
							{"Due_Date", type datetime}, {"Document_Type", type text}, {"Document_No", type text},
							{"Description", type text}, {"Currency_Code", type text}, {"Open", type logical},
							{"Amount", type number}, {"Remaining_Amount", type number}
						}
					)
				in
					#"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

